# Дата вашего рождения и ваш рост.
#
# Используется при расчете нормы потребления калорий в течении дня. Если норма указана вручную
# (см. параметр calories_limit), дату рождения и рост можно не заполнять.
#
# Формат даты настраивается в параметре date_format.
#
birth_date: '29.12.1983'
height:     184
sex: 'man'

# Множитель вашей физической активности.
#
# Примеры значений:
#
# - 1.2 (без спортзала)
# - 1.375 (спортзал до трех раза в неделю)
# - 1.55  (спортзал от трех до пяти раз в неделю)
# - 1.725 (ежедневный спортзал)
#
activity_multiplier: 1.35

# Процент от нормы калорий в день.
#
calories_shortage: 20

# Норма потребления калорий в день.
# 
# Укажите ноль, если хотите, чтобы норма считалась сама по формуле Харриса-Бенедикта
# (приблизительная оценка на основе веса тела, роста и возраста человека).
#
calories_limit: 0

# Норма потребления калорий в день.
# 
# Укажите ноль, если хотите, чтобы норма считалась сама по формуле Харриса-Бенедикта
# (приблизительная оценка на основе веса тела, роста и возраста человека).
#
calories_percent_to_cut_off: 0

# Формат даты. 
#
# Используется в заголовке дневника и при чтении даты рождения.
#
date_format: '%d.%m.%Y'

# Имя директории с архивом дневников.
#
# Предполагается, что директория будет находиться в корневой директории приложения.
#
archive_dirname: 'history'

# Имя файла дневника питания за сегодня.
#
# Предполагается, что файл должен находиться в корневой директории приложения.
#
journal_filename: 'meals.yaml'

# Имя файла справочника продуктов питания.
#
# Предполагается, что файл должен находиться в корневой директории приложения.
#
catalog_filename: 'foods.yaml'

# Имя файла с замерами веса вашего тела.
#
# Предполагается, что файл должен находиться в корневой директории приложения.
#
weights_filename: 'scale.yaml'