# -----------------------------------------------------------------------------
# ПОТРЕБЛЕНИЕ КАЛОРИЙ В ДЕНЬ
#
# Нужно либо указать норму калорий вручную (параметр calories_limit),
# либо указать в этом параметре ноль и заполнить остальные параметры
# раздела. Тогда норма будет считаться автоматически по формуле
# Харриса-Бенедикта (приблизительная оценка на основе веса тела,
# роста и возраста).
# -----------------------------------------------------------------------------

calories_limit: 0             # Норма потребления калорий в день
birth_date:     '29.12.1983'  # Дата вашего рождения в формате "день.месяц.год"
height:         184           # Ваш рост в сантиметрах
sex:            'man'         # Ваш пол (man/women)

# Множитель вашей физической активности.
#
# Примеры значений:
#
# - 1.2 (без спортзала)
# - 1.375 (спортзал до трех раза в неделю)
# - 1.55  (спортзал от трех до пяти раз в неделю)
# - 1.725 (ежедневный спортзал)
#
activity_multiplier: 1.35

# Снижение дневного потребления калорий в процентах.
#
# Например, в норме вы съедаете 2000 ккал в день. Чтобы похудеть, норму калорий нужно урезать —
# допустим, на одну пятую. Тогда указываем значение 20 (1/5 от 100 процентов).
#
calories_shortage: 20

# -----------------------------------------------------------------------------
# ИМЕНА ФАЙЛОВ И ДИРЕКТОРИЙ
#
# Все файлы и директории, указанный ниже, должны находиться
# в корневой директории приложения.
# -----------------------------------------------------------------------------

archive_dirname: 'history' # Имя папки архива дневников

journal_filename: 'meals.yaml'  # Имя файла дневника питания
catalog_filename: 'foods.yaml'  # Имя файла справочника продуктов питания
weights_filename: 'scale.yaml'  # Имя файла с замерами веса вашего тела