# Норма потребления калорий в день.
# 
# Укажите ноль, если хотите, чтобы норма считалась автоматически по формуле Харриса-Бенедикта
# (приблизительная оценка на основе веса тела, роста и возраста).
#
calories_limit: 0

# Дата вашего рождения в формате "день.месяц.год".
#
# Используется при автоматическом расчете нормы потребления калорий в течении дня.
# Если норма указана вручную (см. параметр calories_limit), можно не заполнять.
#
birth_date: '29.12.1983'

# Ваш рост в сантиметрах.
#
# Используется при автоматическом расчете нормы потребления калорий в течении дня.
# Если норма указана вручную (см. параметр calories_limit), можно не заполнять.
#
height: 184

# Ваш пол (man/women).
#
# Используется при автоматическом расчете нормы потребления калорий в течении дня.
# Если норма указана вручную (см. параметр calories_limit), можно не заполнять.
#
sex: 'man'

# Множитель вашей физической активности.
#
# Используется при автоматическом расчете нормы потребления калорий в течении дня.
# Если норма указана вручную (см. параметр calories_limit), можно не заполнять.
#
# Примеры значений:
#
# - 1.2 (без спортзала)
# - 1.375 (спортзал до трех раза в неделю)
# - 1.55  (спортзал от трех до пяти раз в неделю)
# - 1.725 (ежедневный спортзал)
#
activity_multiplier: 1.35

# Снижение дневного потребления калорий в процентах.
#
# Например, в норме вы съедаете 2000 ккал в день. Чтобы похудеть, норму калорий нужно урезать —
# допустим, на одну пятую. Тогда указываем значение 20 (1/5 от 100 процентов).
#
# Используется при автоматическом расчете нормы потребления калорий в течении дня.
# Если норма указана вручную (см. параметр calories_limit), можно не заполнять.
#
calories_shortage: 20

# Имя директории с архивом дневников.
#
# Предполагается, что директория будет находиться в корневой директории приложения.
#
archive_dirname: 'history'

# Имя файла дневника питания за сегодня.
#
# Предполагается, что файл должен находиться в корневой директории приложения.
#
journal_filename: 'meals.yaml'

# Имя файла справочника продуктов питания.
#
# Предполагается, что файл должен находиться в корневой директории приложения.
#
catalog_filename: 'foods.yaml'

# Имя файла с замерами веса вашего тела.
#
# Предполагается, что файл должен находиться в корневой директории приложения.
#
weights_filename: 'scale.yaml'