calories_limit:   1650          # дневной лимит калорий
archive_dirname:  'history'     # имя директории с архивом дневников
journal_filename: 'meals.yaml'  # имя файла дневника
catalog_filename: 'foods.yaml'  # имя файла справочника